# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a packages directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "qoriq-sdk-release"
BBFILE_PATTERN_qoriq-sdk-release := "^${LAYERDIR}/"
BBFILE_PRIORITY_qoriq-sdk-release = "8"
LAYERSERIES_COMPAT_qoriq-sdk-release = "honister kirkstone langdale mickledore master nanbield scarthgap styhead walnascar"

HOSTTOOLS_NONFATAL:append = " whoami sha384sum xxd realpath"

BBFILES_DYNAMIC += " \
    virtualization-layer:${LAYERDIR}/dynamic-layers/virtualization-layer/*/*/*.bb \
    virtualization-layer:${LAYERDIR}/dynamic-layers/virtualization-layer/*/*/*.bbappend \
"

