#!/bin/bash

echo -n "Setting time: "

while true
do
    for s in "https://www.google.com" "https://www.baidu.com" "https://www.yoctoproject.org";do
        t="$(curl -k --connect-timeout 10 -s --head $s | grep ^Date: | head -n 1 | cut -c 6-)"
        if [[ $? -eq 0 ]];then
            date -s "$t"
            break 2
        fi
    done
done
