PACKAGECONFIG:append = " json-c"
PACKAGECONFIG:append:qoriq-arm64 = " numactl"
PACKAGECONFIG:remove:ls1021atwr = "yajl qemu"
PACKAGECONFIG:remove:ls1012ardb = "yajl qemu"
PACKAGECONFIG[json-c] = ",,json-c"
