# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a packages directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "qoriq-bsp-release"
BBFILE_PATTERN_qoriq-bsp-release := "^${LAYERDIR}/"
BBFILE_PRIORITY_qoriq-bsp-release = "8"
LAYERSERIES_COMPAT_qoriq-bsp-release = "honister kirkstone langdale mickledore master nanbield scarthgap styhead walnascar"

LAYERSERIES_COMPAT_virtualization-layer:append = " walnascar"
LAYERSERIES_COMPAT_cloud-services-layer:append = " walnascar"

HOSTTOOLS_NONFATAL:append = " whoami sha384sum xxd realpath"

# debug-tweaks image feature is now removed from walnascar
EXTRA_IMAGE_FEATURES:remove = "debug-tweaks"
MACHINE_FEATURES:append = " \
    allow-empty-password \
    allow-root-login \
    empty-root-password \
    post-install-logging \
"

# Define new EULAs and add them to the list defined in meta-freescale.
# See fsl-eula-unpack.bbclass.
FSL_EULA_FILE_MD5SUM_LA_OPT_NXP_SOFTWARE_LICENSE_V60 = "cf2070b16b9d4acf60a98e8cbc32a25a"

FSL_EULA_FILE_MD5SUMS:append = " \
    ${FSL_EULA_FILE_MD5SUM_LA_OPT_NXP_SOFTWARE_LICENSE_V60} \
"

# The Kernel community has re-organized ARMv7 DTS path in the arch/arm/boot/dts.
KERNEL_DEVICETREE:ls1021atwr = "nxp/ls/ls1021a-twr.dtb"
KERNEL_DEVICETREE:ls1021aqds = "nxp/ls/ls1021a-qds.dtb"

# Reset INITRAMFS_IMAGE_NAME from kernel-fitimage.bbclas
# INITRAMFS_IMAGE_NAME ?= "${@['${INITRAMFS_IMAGE}${IMAGE_MACHINE_SUFFIX}', ''][d.getVar('INITRAMFS_IMAGE') == '']}"
INITRAMFS_IMAGE_NAME="${INITRAMFS_IMAGE}${IMAGE_MACHINE_SUFFIX}${IMAGE_NAME_SUFFIX}"

PREFERRED_VERSION_imx-gpu-viv:ls1028a = "6.4.11.p3.2-aarch64"
PREFERRED_PROVIDER_virtual/mesa:ls1028a   = "mesa-gl"
PREFERRED_PROVIDER_virtual/libgl:ls1028a  = "mesa-gl"

