# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a packages directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "qoriq-bsp-release"
BBFILE_PATTERN_qoriq-bsp-release := "^${LAYERDIR}/"
BBFILE_PRIORITY_qoriq-bsp-release = "8"
LAYERSERIES_COMPAT_qoriq-bsp-release = "whinlatter"

HOSTTOOLS_NONFATAL:append = " whoami sha384sum xxd realpath"

# Define new EULAs and add them to the list defined in meta-freescale.
# See fsl-eula-unpack.bbclass.
FSL_EULA_FILE_MD5SUM_LA_OPT_NXP_SOFTWARE_LICENSE_V62 = "a93b654673e1bc8398ed1f30e0813359"
FSL_EULA_FILE_MD5SUM_LA_OPT_NXP_SOFTWARE_LICENSE_V63 = "bc649096ad3928ec06a8713b8d787eac"

FSL_EULA_FILE_MD5SUMS:append = " \
    ${FSL_EULA_FILE_MD5SUM_LA_OPT_NXP_SOFTWARE_LICENSE_V62} \
    ${FSL_EULA_FILE_MD5SUM_LA_OPT_NXP_SOFTWARE_LICENSE_V63} \
"

# The Kernel community has re-organized ARMv7 DTS path in the arch/arm/boot/dts.
KERNEL_DEVICETREE:ls1021atwr = "nxp/ls/ls1021a-twr.dtb"
KERNEL_DEVICETREE:ls1021aqds = "nxp/ls/ls1021a-qds.dtb"

# Reset INITRAMFS_IMAGE_NAME from kernel-fitimage.bbclas
# INITRAMFS_IMAGE_NAME ?= "${@['${INITRAMFS_IMAGE}${IMAGE_MACHINE_SUFFIX}', ''][d.getVar('INITRAMFS_IMAGE') == '']}"
INITRAMFS_IMAGE_NAME = "${INITRAMFS_IMAGE}${IMAGE_MACHINE_SUFFIX}${IMAGE_NAME_SUFFIX}"

PREFERRED_VERSION_imx-gpu-viv:ls1028a = "6.4.11.p4.2-aarch64"
PREFERRED_VERSION_weston:ls1028a = "14.0.2.imx"
PREFERRED_VERSION_wayland-protocols:ls1028a = "1.41.imx"
PREFERRED_VERSION_libdrm:ls1028a = "2.4.123.imx"

PREFERRED_PROVIDER_virtual/mesa:ls1028a       = "mesa-gl"
PREFERRED_PROVIDER_virtual/libgl:ls1028a      = "mesa-gl"
PREFERRED_PROVIDER_virtual/libgles1:ls1028a   = "imx-gpu-viv"
PREFERRED_PROVIDER_virtual/libgles2:ls1028a   = "imx-gpu-viv"
PREFERRED_PROVIDER_virtual/egl:ls1028a        = "imx-gpu-viv"
PREFERRED_PROVIDER_virtual/libopencl1:ls1028a = "imx-gpu-viv"

# Some gstream plugins require "commercial" be set in LICENSE_FLAGS_ACCEPTED
# For exmaple, gstreamer1.0-plugins-ugly-asf/gstreamer1.0-libav
# uncomment the below one line to include them into fsl-image-multimedia-full
LICENSE_FLAGS_ACCEPTED:append:ls1028a = " commercial"

BBMASK += "meta-freescale/recipes-bsp/u-boot/u-boot-qoriq_2025.04.bb"
