#!/bin/bash

while true
do
	gatewayip=$(ip route show | grep default | awk '{print $3}')
	ping -c 3 -w 5 $gatewayip  1>/dev/null 2>/dev/null
	if [[ $? = 0 ]];then
		echo "network connect well"
		break
	fi
	sleep 2
done
